- corelib-web/src/main/java/eu/europeana/corelib/web/support/ReportingMessageSource.java
After this change, the similar named pull request in portal is required as well...
> Changed the ReportingReloadableMessageSource to ReportingMessageSource

- corelib-dereference/src/main/java/eu/europeana/corelib/dereference/impl/VocabularyMongoServerImpl.java
- corelib-edm-definitions/src/main/resources/eu/EDM-COMMON-MAIN.xsd
- corelib-edm-definitions/src/main/resources/eu/RDF.xsd
- corelib-lookup/src/main/java/eu/europeana/corelib/lookup/impl/CollectionMongoServerImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/utils/EdmUtils.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/utils/construct/FullBeanHandler.java
> Reindexing take2

- corelib-definitions/src/main/java/eu/europeana/corelib/definitions/edm/entity/Aggregation.java
- corelib-definitions/src/main/java/eu/europeana/corelib/definitions/edm/entity/WebResource.java
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/SearchServiceImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/bean/impl/FullBeanImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/derived/AttributionSnippet.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/AggregationImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/WebResourceImpl.java
Contains the refactored Attributionsnippet code coming from the api Fullview
> last tweaks attributionsnippet

- corelib-web/src/main/resources/internal/corelib-web-email.xml
300: Ensure API emails are sent from api@europeana.eu
> 300: Ensure API emails are sent from api@europeana.eu

- corelib-db/src/main/java/eu/europeana/corelib/db/service/UserService.java
- corelib-db/src/main/java/eu/europeana/corelib/db/service/impl/UserServiceImpl.java
- corelib-db/src/test/java/eu/europeana/corelib/db/service/UserServiceTest.java
#95: saved searches update method
> #95: saved searches update method

- corelib-storage/src/main/java/eu/europeana/corelib/edm/utils/EdmUtils.java
in method private static <T> List<T> convertListFromArray(Class<T> clazz, String[] vals) {
the following line was incorrect:
if (obj.getClass().isAssignableFrom(ResourceType.class)) {
I reversed it to:
if (ResourceType.class.isAssignableFrom(obj.getClass())) {
the differences in line numbers are due to some reformatting; that one line is all that is really changed
> fixed by reversing isAssignableFrom statement, line 1002 / 998

- corelib-storage/src/main/java/eu/europeana/corelib/solr/derived/AttributionSnippet.java
Patrick, can you merge this one as well? This one actually contains the rightsstatement.org labels code change. Thanks.
PS it just occurred to me that you are Dutch and are called Patrick, and there's an Irish guy in our room who is called Lutz :)
All we need now is a German guy named Klaas, Piet, Wim or Karel in order to make the circle complete!
> added labels for rightsstatment url's

- corelib-web/src/test/java/eu/europeana/corelib/web/service/SoundCloudApiServiceTest.java
- pom.xml
> Fixed soundcloud https in unit test

- corelib-db/src/test/resources/corelib-db-test.xml
- corelib-media-storage/pom.xml
- corelib-media-storage/src/main/java/eu/europeana/corelib/service/impl/swift/generic/EuropeanaObjectStorageClientImpl.java
- corelib-media-storage/src/main/resources/corelib-media-storage-context.xml
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/SearchServiceImpl.java
- corelib-web/src/main/resources/corelib-web-context.xml
- corelib-web/src/main/resources/internal/corelib-web-contentreuseframework.xml
- corelib-web/src/test/resources/corelib-web-test.xml
> #393-read-thumbnails-from-S3

- corelib-definitions/pom.xml
- corelib-edm-definitions/pom-generate.xml
- corelib-edm-definitions/pom.xml
- corelib-lookup/pom.xml
- corelib-media-storage/pom.xml
- corelib-search/pom.xml
- corelib-storage/pom.xml
- corelib-sugarcrm/bindings/pom.xml
- corelib-web/pom.xml
- pom.xml
#424 Release prep:
- now using europeana parent pom
- split up api and corelib
> #424-release-prep

- corelib-common-storage/pom.xml
- corelib-db/pom.xml
- corelib-definitions/pom.xml
- corelib-dereference/pom.xml
- corelib-edm-definitions/pom.xml
- corelib-hierarchies/pom.xml
- corelib-lookup/pom.xml
- corelib-media-storage/pom.xml
- corelib-search/pom.xml
- corelib-storage/pom.xml
- corelib-sugarcrm/bindings/pom.xml
- corelib-sugarcrm/client/pom.xml
- corelib-utils/pom.xml
- corelib-web/pom.xml
- pom.xml
switched to dynamic version for corelib and it's modules, for easy branch snapshots versioning
> dynamic maven versions

- corelib-media-storage/src/main/java/eu/europeana/corelib/service/impl/EuropeanaObjectStorageClientImpl.java
En toen knikte de prinses, want ze hield erg veel van zgn. koeckebackemuziek.
> Make sure we include a lastModified date when creating a mediafile

- corelib-common-storage/src/main/java/eu/europeana/corelib/storage/MongoProvider.java
- corelib-common-storage/src/main/java/eu/europeana/corelib/storage/impl/MongoProviderImpl.java
- corelib-db/pom.xml
- corelib-db/src/main/java/eu/europeana/corelib/db/wrapper/ApiMongoConnector.java
- corelib-db/src/main/resources/internal/corelib-db-datasource.xml
- corelib-db/src/test/java/eu/europeana/corelib/db/EmbeddedMongoProvider.java
- corelib-definitions/src/main/resources/test-config/europeana-test.properties
- corelib-dereference/src/main/resources/internal/corelib-solr-dereference-datasource.xml
- corelib-dereference/src/main/resources/internal/corelib-solr-dereference-server.xml
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/SearchServiceImpl.java
- corelib-search/src/main/resources/internal/corelib-search-datasource.xml
- corelib-search/src/main/resources/internal/corelib-search-server.xml
- corelib-search/src/test/java/eu/europeana/corelib/mocks/EmbeddedMongoProvider.java
- corelib-storage/src/main/java/eu/europeana/corelib/mongo/server/impl/EdmMongoServerImpl.java
This commit also includes:
- bug fix #708 where WebResourceMetaInfo would always be retrieved from the europeana database (and not necessarily the one set in the
europeana.properties file)
- various changes and optimization to the way mongo and morphia connections are set up (unnecessary ones are removed)
- consolidated the various mongo settings in europeana.properties
> Connections to Mongo are now done via a single MongoClientURI (fix #697)

- corelib-media-storage/src/main/java/eu/europeana/corelib/service/MediaStorageClient.java
- corelib-media-storage/src/main/java/eu/europeana/corelib/service/impl/EuropeanaObjectStorageClientImpl.java
- pom.xml
This commit also includes switching to object-storage 1.4 that contains speed improvements and new faster methods (such as isAvailable() and retrieveMetaData())
> Changes related to the update of object-storage to v 1.4, see #758

- corelib-hierarchies/src/main/java/eu/europeana/corelib/neo4j/server/Neo4jServer.java
- corelib-hierarchies/src/main/java/eu/europeana/corelib/neo4j/server/impl/Neo4jServerImpl.java
- corelib-search/src/main/java/eu/europeana/corelib/search/SearchService.java
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/SearchServiceImpl.java
> added offset param to preceding- and followingsiblings methods

- corelib-db/src/test/resources/corelib-db-test.xml
- corelib-hierarchies/src/main/java/eu/europeana/corelib/neo4j/server/impl/Neo4jServerImpl.java
- corelib-search/src/main/java/eu/europeana/corelib/search/Neo4jSearchService.java
- corelib-search/src/main/java/eu/europeana/corelib/search/SearchService.java
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/Neo4jSearchServiceImpl.java
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/SearchServiceImpl.java
- corelib-search/src/main/java/eu/europeana/corelib/search/impl/WebMetaInfo.java
- corelib-search/src/main/resources/internal/corelib-search-server.xml
- corelib-search/src/test/resources/corelib-solr-test.xml
- pom.xml
looks good, thanks for splitting up that honking SearchServiceImpl thing :) - this is way better
> Ea 992 referenced by iiif

- corelib-common-storage/pom.xml
- corelib-db/pom.xml
- corelib-definitions/pom.xml
- corelib-edm-definitions/pom.xml
- corelib-edm-definitions/src/main/resources/eu/CONTEXTS.xsd
- corelib-hierarchies/pom.xml
- corelib-lookup/pom.xml
- corelib-media-storage/pom.xml
- corelib-search/pom.xml
- corelib-storage/pom.xml
- corelib-storage/src/main/java/eu/europeana/corelib/edm/utils/EdmUtils.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/utils/EdmWebResourceUtils.java
- corelib-sugarcrm/bindings/pom.xml
- corelib-sugarcrm/client/pom.xml
- corelib-utils/pom.xml
- corelib-web/pom.xml
- pom.xml
Contains changes from both 1261 and 1260
> Ea 1261 fix place of birth and death

- pom.xml
> EA-1506 updated Spring Core & Security versions

- corelib-db/pom.xml
- corelib-db/src/main/java/eu/europeana/corelib/db/entity/relational/custom/TagCloudItem.java
- corelib-definitions/src/main/java/eu/europeana/corelib/definitions/edm/beans/BriefBean.java
- corelib-storage/pom.xml
- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/AudioMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/ImageMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/TextMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/VideoMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/WebResourceMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/bean/impl/ApiBeanImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/bean/impl/BriefBeanImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/bean/impl/FullBeanImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/bean/impl/RichBeanImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/AddressImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/AgentImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/AggregationImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/ConceptImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/ContextualClassImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/DatasetImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/EuropeanaAggregationImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/LicenseImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/OrganizationImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/PlaceImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/ProvidedCHOImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/ProxyImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/TimespanImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/WebResourceImpl.java
For testing merging the changes to one branch
> Ea 354 record api return jsonld fix

- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/AudioMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/WebResourceImpl.java
Have added the codec in AudioMetaInfoImpl
have changed the logic of setting the codecName (getEdmCodecName) in WebResourceImpl
> MET-2296 added codecname in audioMetaInfo

- corelib-storage/src/main/java/eu/europeana/corelib/edm/model/metainfo/TextMetaInfoImpl.java
- corelib-storage/src/main/java/eu/europeana/corelib/solr/entity/WebResourceImpl.java
@SrishtiSingh-eu can you merge this when Patrick has seen the comment in the ticket?
> Ea 1872 record api rdf type not being shown

- corelib-web/src/main/java/eu/europeana/corelib/web/exception/ProblemType.java
see notes for https://europeana.atlassian.net/browse/EA-1826
> Ea 1826 apikey service integration
